### ISSUE TITLE
Can't parse messages with attachments

### ISSUE THREAD

**Issue by fiol92** [r-lib/gmailr#112]
The message(id) function works fine for normal emails, but doesn't provide any input for emails with any form of attachment, such as a company logo. It does provide ID, To, From, Date and Subject of the message, but not the content, neither with using body() nor printing the item. 

This is true regardless of the format used in the message function (i.e. "full", "minimal", "raw" etc.), and the message. The only way to retrieve any information from such messages is by using the msg$snippet.

**Comment by jimhester** [comment]
I believe this is fixed in the devel version of gmailr, but it would still be useful to have an example message that exhibits the behavior you describe, it almost surely depends on the type of the mime message.

**Comment by fiol92** [comment]
Thank you for the response! The problem remains in the updated version of gmailr. 

The output of gm_message(id, format = full):
Id: [id]
To: "y@gmail.com" <y@gmail.com>
From: "x" <x@gmail.com>
Date: Wed, 4 Sep 2019 05:47:35 +0000
Subject: SV: Controlling
Attachments: 'image001.jpg'

The actual email contains a few lines of text, typically with a banner or logo at the end of the message.

**Comment by jimhester** [comment]
Sorry I can't reproduce the issue, and without the ability to do so I have no way to fix it. Likely you need to specify the `type` of the message that contains the body, e.g. it defaults to `text/plain`, but it may actually need to be `text/html`, e.g. `gm_body(msg, type = "text/html")`.

**Comment by fiol92** [comment]
Sadly that does not help. I tried sending two identical emails to myself, where one included an attached png-file. The .png message can't, as previously be parsed, while the other message was parsed without any difficulties. 

The two messages to have different mime types, where the attachment one is multipart/mixed, while the other one is multipart/alternative, which might affect the issue.  If you need any specific info to reproduce the issue, let me know.

**Comment by jennybc** [comment]
I'm invoking the statute of limitations on this one. Maybe I'll re-encounter it myself or a new issue with a reprex will appear one day.
