### ISSUE TITLE
HTML File as message body

### ISSUE THREAD

**Issue by maaraaj** [r-lib/gmailr#54]
I have a HTML file that I want to be message body of the emails I am sending. 
How to I insert my HTML file in the code

**Comment by pgg1309** [comment]
Hi,
I'm interested in replicating the example below using gmailr.
https://www.r-bloggers.com/scheduling-r-markdown-reports-via-email/

It basically generates an html file using Rstudio and then automatically sends the e-mail with the html in the body. Would it be possible using gmailr package? I've tried some simple ways but it did not work. 
Any help?

**Comment by jimhester** [comment]
Use `gh_mime() %>% gh_html_body()`, there were previously some bugs that made this not work in some cases, but they should now be resolved.

**Comment by sandeepgangarapu** [comment]
It still does not work. I got this warning and a blank email

Warning message:
In charToRaw(x) : argument should be a character vector of length 1
all but the first element will be ignored

Looks like HTML info should be formatted in a certain way

**Comment by armenic** [comment]
`paste() and readLines()` did the job for me.

```R
  gm_mime() %>%
    gm_to(email_to) %>%
    gm_subject(
      sprintf("FI (PDAA Member), %s, Exploratory Onboarding", to_name)
    ) %>%
    gm_html_body(paste(readLines("gmailr.html"), collapse = "")) %>%
    gm_attach_file("FI-Footer-logo.png", id = "signature")
```

**Comment by ratnexa** [comment]
I still cannot use it via html file from markdown, the message isn't shown properly on desktop: 

![image](https://user-images.githubusercontent.com/66443052/125514012-2941356a-b97d-4b4d-945b-08a8c05d1ee0.png)

How can I achieve it showing properly?
